### Creates a new patient entity
POST http://localhost:4000/patients/
Content-Type: application/json

{
  "first_name": "Moreshwar",
  "last_name": "Nabar",
  "date_of_birth": "1996-06-18",
  "email": "moray@email.com",
  "address": "Earth",
  "registered_date": "2024-06-18"
}

###