### Creates a new patient entity
POST http://localhost:4000/patients/
Content-Type: application/json

{
  "first_name": "Sara",
  "last_name": "Lance",
  "date_of_birth": "1987-12-25",
  "email": "sara@legends.com",
  "address": "Waverider",
  "registered_date": "2025-03-19"
}

###